
package gui;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPage = new javax.swing.JPanel();
        usr_login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginSubmit = new javax.swing.JButton();
        pass_login = new javax.swing.JPasswordField();
        QUIT = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        combo_role = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPage.setBackground(new java.awt.Color(0, 51, 51));
        loginPage.setForeground(new java.awt.Color(0, 51, 51));
        loginPage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        usr_login.setBackground(new java.awt.Color(153, 255, 255));
        usr_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usr_loginActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Username :");

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Password :");

        loginSubmit.setBackground(new java.awt.Color(255, 51, 51));
        loginSubmit.setForeground(new java.awt.Color(0, 51, 51));
        loginSubmit.setText("Login");
        loginSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginSubmitMouseClicked(evt);
            }
        });
        loginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitActionPerformed(evt);
            }
        });

        pass_login.setBackground(new java.awt.Color(153, 255, 255));
        pass_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_loginActionPerformed(evt);
            }
        });

        QUIT.setBackground(new java.awt.Color(255, 51, 51));
        QUIT.setText("QUIT");
        QUIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUITActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 51, 51));
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        combo_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select role", "Customer", "Manager", "Admin" }));
        combo_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_roleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPageLayout = new javax.swing.GroupLayout(loginPage);
        loginPage.setLayout(loginPageLayout);
        loginPageLayout.setHorizontalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPageLayout.createSequentialGroup()
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QUIT))
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPageLayout.createSequentialGroup()
                                .addComponent(reset)
                                .addGap(53, 53, 53)
                                .addComponent(loginSubmit))
                            .addGroup(loginPageLayout.createSequentialGroup()
                                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginPageLayout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPageLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usr_login, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(pass_login))))
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        loginPageLayout.setVerticalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usr_login, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginSubmit)
                    .addComponent(reset))
                .addGap(29, 29, 29)
                .addComponent(QUIT)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitActionPerformed
                String username = usr_login.getText();
                String password = new String(pass_login.getPassword());

                if(combo_role.getSelectedItem().equals("Manager")){
                //function for login customer
                  File f = new File("managerAcc.txt");
                  boolean status = false;
                  try {

                      Scanner sc = new Scanner(f);
                      sc.nextLine();
                      while(sc.hasNextLine()){
                      String row[] = sc.nextLine().split("#");
                      String idInFile = row[0];
                      String passInFile = row[1];
                      if((username.equalsIgnoreCase(idInFile)) && (password.equalsIgnoreCase(passInFile))){
                          manager m = new manager();
                          m.setVisible(true);
                          this.setVisible(false);
                          status = true;
                          break;
                      }else{JOptionPane.showMessageDialog(this, "wrong id or password~");}
                    }
                      if(status == false)
                      {
                          JOptionPane.showMessageDialog(this, "wrong id or password~");
                      }
                  } catch (FileNotFoundException ex) {
                      System.out.println(ex);
                  }
        }      
        
                else if(combo_role.getSelectedItem().equals("Customer")){
                //function for login customer
                  File fi = new File("customerAcc.txt");
                  boolean status = false;
                  try{
                      Scanner sc = new Scanner(fi);
                      sc.nextLine();
                      while(sc.hasNextLine()){
                      String row[] = sc.nextLine().split("#");
                      String idInFile = row[0];
                      String passInFile = row[1];                   
                      if((username.equalsIgnoreCase(idInFile)) && (password.equalsIgnoreCase(passInFile))){
                          shop s = new shop();
                          s.setVisible(true);
                          this.setVisible(false);
                          status = true;
                          break;
                      }
                    }
                      if(status == false)
                      {
                          JOptionPane.showMessageDialog(this, "wrong id or password~");
                      }
                    
                  } catch (FileNotFoundException ex) {
                      System.out.println(ex);
                  }
        }
                else if(combo_role.getSelectedItem().equals("Admin")){
                //function for login admin
                  File fr = new File("admin.txt");
                  boolean status = false;
                  try{
                      Scanner sc = new Scanner(fr);
                      sc.nextLine();
                      while(sc.hasNextLine()){
                      String row[] = sc.nextLine().split("#");
                      String idInFile = row[0];
                      String passInFile = row[1];
                      if((username.equalsIgnoreCase(idInFile)) && (password.equalsIgnoreCase(passInFile))){
                          admin a = new admin();
                          a.setVisible(true);
                          this.setVisible(false);                          
                          status = true;
                          break;
                      }else{JOptionPane.showMessageDialog(this, "wrong id or password~");}
                    }
                    if(status == false)
                     {
                       JOptionPane.showMessageDialog(this, "wrong id or password~");
                     }
                  } catch (FileNotFoundException ex) {
                      System.out.println(ex);
                  }
        }
        else if(combo_role.getSelectedItem().equals("select role")){
            JOptionPane.showMessageDialog(this, "Please select a role!");
        }
        else{JOptionPane.showMessageDialog(this, "wrong id or password~^");}
    }//GEN-LAST:event_loginSubmitActionPerformed

    
    private void loginSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginSubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginSubmitMouseClicked

    private void usr_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usr_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usr_loginActionPerformed

    private void pass_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_loginActionPerformed

    private void QUITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QUITActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // clean text file to "null":
        usr_login.setText("");
        pass_login.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void combo_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_roleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QUIT;
    private javax.swing.JComboBox<String> combo_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel loginPage;
    private javax.swing.JButton loginSubmit;
    private javax.swing.JPasswordField pass_login;
    private javax.swing.JButton reset;
    private javax.swing.JTextField usr_login;
    // End of variables declaration//GEN-END:variables
}
